(ns ui.main.input.key-handler
  (:require [ui.actions :as actions]))

;; TODO shouldn't be part of key-handler
(defn get-title-el []
  (.getElementById js/document "search-input"))

;; TODO make use of common/handle-keys*
(defn handle-keys [*state]
  #(let [code (.-code %)]
    (.stopPropagation %)
    (when (and (= code "Enter"))
      (.preventDefault %)
      (cond
        (or (and (.-shiftKey %)
                 (= :contexts (:active-search @*state)))
            (and (= :contexts (:active-search @*state))
                 (= 0 (count (:contexts @*state)))))
        (do
          (actions/new-context! *state {:title (.-value (get-title-el))})
          (set! (.-value (get-title-el)) ""))
        (or (and (.-shiftKey %)
                 (not (:search-globally? @*state))
                 (:selected-context @*state)
                 (not (:selected-issue @*state)))
            (and (not (:search-globally? @*state))
                 (:selected-context @*state)
                 (not (:selected-issue @*state))
                 (= 0 (count (:issues @*state)))))
        (when-not (:enter-pressed? @*state)
          (swap! *state assoc :enter-pressed? true)
          (actions/new-issue! *state {:title (.-value (get-title-el))})
          (set! (.-value (get-title-el)) ""))
        #_(swap! *state dissoc nil)
        (= :contexts (:active-search @*state))
        (actions/select-first-context! *state)
        (= :issues (:active-search @*state))
        (actions/select-first-issue! *state)))
    (when (and (.-altKey %)
               (:selected-issue @*state)
               (= "KeyA" code))
      (.preventDefault %)
      (actions/link-with-global-search! *state))
    (when (and (= code "KeyI")
               (.-altKey %))
      (.preventDefault %)
      (set! (.-value (get-title-el)) "")
      (actions/start-global-search! *state))
    (when (and (= code "KeyC")
               (.-altKey %))
      (swap! *state dissoc :search-globally? :q :active-search)
      (actions/start-context-search *state))
    (when (and (= code "KeyD")
               (not (:selected-issue @*state))
               (:selected-context @*state)
               (.-altKey %))
      (.preventDefault %)
      (set! (.-value (get-title-el)) "")
      (actions/link-context-with-global-search! *state))
    (when (and (= code "KeyD")
               (.-altKey %)
               (:selected-issue @*state))
      (swap! *state assoc :active-search :contexts)
      (actions/start-linking-context *state))
    (when (= code "Escape")
      (cond (or (and (:search-globally? @*state)
                     (:selected-context @*state))
                (:selected-issue @*state)
              ;; TODO (not (:selected-context @*state)) not necessary?
                )
            (actions/quit-search! *state)
            (and (.-altKey %)
                 (= :issues (:active-search @*state))
                 (:selected-context @*state))
            (actions/quit-search! *state)
            :else
            (when (seq (:selected-secondary-contexts (:data (:selected-context @*state))))
              (actions/deselect-secondary-contexts! *state))))))
