#!/bin/bash
# Regenerate docker/compose.ports.yml from the detected PORT/SHADOW_PORT.
# The main docker-compose.yml has no `ports:` of its own; this override is
# layered in via COMPOSE_FILE so the host bindings exactly match whatever
# the user has in .envrc / config.edn / shadow-cljs.edn -- no `${PORT:-...}`
# fallbacks scattered through the YAML.
set -e

PORT="${1:?usage: write-compose-ports.sh PORT SHADOW_PORT}"
SHADOW_PORT="${2:?}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docker/compose.ports.yml"

cat > "$OUT" <<EOF
# Auto-generated by 'make box'. Do not edit by hand -- changes are clobbered
# on every run. Source of truth is .envrc / config.edn / shadow-cljs.edn
# (see scripts/detect-ports.sh).
services:
  box:
    ports:
      - "${PORT}:${PORT}"
      - "${SHADOW_PORT}:${SHADOW_PORT}"
EOF
